server:
  port: 8080
  servlet:
    context-path:
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: root
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true